# Generated by Django 5.0.3 on 2024-04-11 15:23

from django.db import migrations
from transactions.models import Category

def add_default_categories(apps, schema_editor):
    Category.objects.create(name='Income')
    Category.objects.create(name='Expenses')
    Category.objects.create(name='Savings')
    Category.objects.create(name='Investments')


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]
